<?php
namespace api\controllers;
use yii\data\ActiveDataProvider;
use common\models\User;
use yii\rest\ActiveController;
use yii\data\Pagination; //分页

class UserController extends ActiveController
{
    public $modelClass = 'common\models\User';
    
    public function actions()
    {
        $action= parent::actions(); // TODO: Change the autogenerated stub
        unset($action['index']);
        unset($action['create']);
        unset($action['update']);
        unset($action['delete']);
        return $action;
    }
    
    public function actionIndex()
    {
        //你的代码
        $hello = json_encode(array('tom'=>1,'jack'=>2));
        return $hello;
    }

    /**
     * 退出登录
     */
    public function actionLogout()
    {
	    return new ActiveDataProvider([
            'query' => User::find(),
            // 设置分页，比如每页200个条目
            'pagination' => new Pagination(['pageSize' => 10])
        ]);
    }
}